# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('os', models.CharField(max_length=128, verbose_name='系统版本')),
                ('cpu_kernel', models.CharField(max_length=128, verbose_name='CPU内核版本')),
                ('mem_total', models.FloatField(blank=True, null=True, verbose_name='total内存GB')),
                ('mem_used', models.FloatField(blank=True, null=True, verbose_name='used内存GB')),
                ('disk_capacity', models.FloatField(blank=True, null=True, verbose_name='磁盘容量GB')),
                ('latest_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '服务器表',
                'db_table': 'server_machine',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=128, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user_profile',
            },
        ),
    ]
