# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.SlugField(max_length=64, verbose_name='模块名')),
                ('module_type', models.IntegerField(choices=[(1, 'ansible'), (2, 'shell'), (3, 'salt')], default=1, verbose_name='模块类型')),
                ('module_lang', models.IntegerField(choices=[(1, 'python'), (2, 'shell'), (3, '其他')], default=1, verbose_name='开发语言')),
                ('module_info', models.TextField(verbose_name='模块概述')),
                ('module_path', models.FilePathField(verbose_name='模块路径')),
                ('latest_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
    ]
