# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180307_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64, verbose_name='主机组名')),
                ('Summary', models.TextField(max_length=255, verbose_name='主机组概述')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(blank=True, null=True, to='db.InventoryGroups', verbose_name='主机组')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Server', verbose_name='主机名')),
            ],
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='host',
            field=models.ManyToManyField(null=True, to='db.InventoryHosts', verbose_name='主机 ID'),
        ),
    ]
