# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180307_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorygroups',
            options={'verbose_name_plural': 'Ansible 主机组表'},
        ),
        migrations.AlterModelOptions(
            name='inventoryhosts',
            options={'verbose_name_plural': 'Ansible 主机表'},
        ),
        migrations.AddField(
            model_name='connectioninfo',
            name='auth_type',
            field=models.IntegerField(choices=[(0, 'ssh-password'), (1, 'ssh-key')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='connectioninfo',
            unique_together=set([('auth_type', 'remote_user', 'password')]),
        ),
        migrations.AlterModelTable(
            name='connectioninfo',
            table='connection_info',
        ),
        migrations.AlterModelTable(
            name='inventorygroups',
            table='inventory_groups',
        ),
        migrations.AlterModelTable(
            name='inventoryhosts',
            table='inventory_hosts',
        ),
        migrations.RemoveField(
            model_name='connectioninfo',
            name='ssh_private_key_path',
        ),
    ]
