# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20180307_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='host',
            field=models.ManyToManyField(to='db.InventoryHosts', verbose_name='主机 ID'),
        ),
        migrations.AlterField(
            model_name='inventoryhosts',
            name='group',
            field=models.ManyToManyField(default='', to='db.InventoryGroups', verbose_name='主机组'),
        ),
    ]
