# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20180308_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableinfo',
            name='groups',
            field=models.ManyToManyField(null=True, to='db.InventoryGroups', verbose_name='归属组'),
        ),
    ]
