# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_inventorygroups_parent_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectioninfo',
            options={'verbose_name_plural': 'SSH 连接信息表'},
        ),
        migrations.AlterField(
            model_name='variableinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='db.InventoryGroups', verbose_name='归属组'),
        ),
        migrations.AlterField(
            model_name='variableinfo',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, to='db.InventoryHosts', verbose_name='归属主机'),
        ),
    ]
